### ISSUE TITLE
Waiting for open source 

### ISSUE THREAD

**Issue by itzharshit** [Sumitthakurtech/ecom-singlepage#1]
Hey sumit, I really like your project and I think it's awesome. But I have a question: why don't you make it open source? I think a lot of people would benefit from seeing your code and learning from it. Plus, you could get feedback and contributions from other developers who are interested in your work. I'm not trying to pressure you or anything, but I think it would be cool if you could share your project with the world. What do you think?

**Comment by Sumitthakurtech** [comment]
Hi Harshit (@itzharshit),
Really appreciate your suggestion it sound brillant

**Comment by Sumitthakurtech** [comment]
Hi Harshit 
Appreciate your suggestion mate ,consider it done! :)
